### ISSUE TITLE
Add traffic info for more lines

### ISSUE THREAD

**Issue by Sitavi** [corenting/ParisTransportTraffic#118]
It would be a great addition to have traffic information from other lines than those managed by RATP, such as RER C to E, suburban trains and trams not present on the application (also, I have no info on tram T1).  It would surely be necessary to go through the API of IDFM and / or SNCF.

**Comment by corenting** [comment]
I finally had the time to start working on it, it's a work-in-progress (https://github.com/corenting/ParisTransportTraffic/pull/200)
